# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyO50Qc6VYeQzg1wzPyoQCc0Uu0u3yH4
"""

##Probar el modelo
import joblib
modelo = joblib.load('modelo_obesidad.pkl')

datos = [[1,21,1.62,64,1,0,2,3,1,0,2,0,0,1,0,3]]
resultado = modelo.predict(datos)
print(resultado)

# Creación API
from flask import Flask, request, jsonify
import joblib
import numpy as np
import os

app = Flask(__name__)

# Cargar correctamente el modelo
model = joblib.load('modelo_obesidad.pkl')

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.get_json()
        features = data['features']

        # Convertir a array para predicción
        features = np.array(features).reshape(1, -1)
        prediction = model.predict(features)

        return jsonify({'prediction': prediction.tolist()})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)

import joblib
model = joblib.load('modelo_obesidad.pkl')
print(type(model))

